### ISSUE TITLE
Convert into Metanorma AsciIDoc format

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ogc-2D-Tile-Matrix-Set#1]
@metanorma/editors can you please help convert this document (under `standard/`) to Metanorma, with the proper metadata set? Thanks!

From: https://github.com/opengeospatial/ogc-metanorma-testing/issues/75#issue-1227820881

**Comment by manuelfuenmayor** [comment]
@ronaldtse the conversion of this document is ready for review in https://github.com/metanorma/ogc-2D-Tile-Matrix-Set/pull/2.

**Comment by manuelfuenmayor** [comment]
In addition, I have applied the fixing of some typos reported in https://github.com/opengeospatial/2D-Tile-Matrix-Set/pull/73.

**Comment by ronaldtse** [comment]
There were a couple editorial issues I fixed:

1. In a commit, use a more descriptive commit message than "Add files via upload"
2. For tables: (tables: ddf2ab3236746605d8307ca829cb8e700c53dc7f)
    1. For the table body cells, please split the cells delimiters at every column row, if the contents of the cell are rather long. (the entire row goes over 80 chars)
    2. For the table header cells, try to keep them on one line unless they are too long (i.e. over 80 chars).
    3. For table widths, *always* remove the `[width=xx%]` because they do not make any sense in Metanorma.
    4. For table cols, *always* use `[cols="a,2a"]` over `[cols="1,2"]` or the implicit definition, because it is very difficult to know how things look like and people often enter links etc. in the cells.
3. For the bibliography, there is no need to tag it as `[appendix]` (72d896ab9dc7cdf7666ac4be55480d13087a564a)
4. For OGC preface, use `== Preface` not `.Preface` because of the ordering requirements.
5. When we convert a document, always apply the Metanorma CI structure (see 642f12410199471f586193bca77fc2f6c63226c0)
