### ISSUE TITLE
(URGENT) Failure of footnote reference syntax `footnote:ref[]`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/ogc-2D-Tile-Matrix-Set#4]
Being fixed in https://github.com/metanorma/metanorma-ogc/issues/383

In https://github.com/metanorma/isodoc/issues/155 the syntax `footnote:ref[]` can be used to reuse a footnote called `ref`.

It is not working in OGC HTML and PDF.

```adoc
.Parts of BoundingBox data structure
[cols="a,a,a,a",options="header"]
|===
| Names | Definition | Data type and values | Multiplicity and use

| lowerLeft
| Coordinates of bounding box corner at which the value of each coordinate
normally is the algebraic minimum within this bounding box

footnote:a[Values other than the minimum and maximum may be used as discussed below.]

| Ordered sequence of double values

footnote:b[The number of axes included, and the order of these axes, as specified by the referenced CRS.]
| One (mandatory)

| upperRight
| Coordinates of bounding box corner at which the value of each coordinate
normally is the algebraic maximum within this bounding box{blank}footnote:a[]
| Ordered sequence of double values{blank}footnote:b[]
| One (mandatory)

...
```

Rendered as:

PDF:
<img width="657" alt="Screenshot 2022-05-26 at 2 29 35 AM" src="https://user-images.githubusercontent.com/11865/170340118-7845f024-9a7b-4d31-a73c-42ff4638b8ff.png">

HTML:
<img width="887" alt="Screenshot 2022-05-26 at 2 29 59 AM" src="https://user-images.githubusercontent.com/11865/170340242-96da1305-98cd-40ba-aaf9-42993a8b6455.png">

Document: https://github.com/metanorma/ogc-2D-Tile-Matrix-Set

**Comment by opoudjis** [comment]
This is an Asciidoctor issue. The footnote cross-references will work so long as you don't insist on Asciidoctor styling of the cells, and use just `[options="header"]`.
